apiVersion: v1
kind: ReplicationController
metadata:
  labels:
      name: traefik-v1
  name: traefik-v1
  namespace: loadbalancer
spec:
  replicas: 1
  selector:
      app: traefik
  template:
    metadata:
      labels:
          app: traefik
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: traefik-ingress-controller
      hostNetwork: true
      containers:
        - name: traefik-ingress-lb
          image: traefik
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 80
              name: http
            - containerPort: 443
              hostPort: 443
              name: https
          args:
          - --web.address=:8580
          - --web
          - --kubernetes
          - --logLevel=DEBUG
          volumeMounts:
            - name: traefik-config
              mountPath: "/etc/traefik/traefik.toml"
            - name: acmjson
              mountPath: "/acme.json"

      volumes:
        - name: traefik-config
          hostPath:
            path: "/opt/kubernetes/kube-system/traefik-ingress-lb/traefik.toml"
        - name: acmjson
          hostPath:
            path: "/opt/kubernetes/kube-system/traefik-ingress-lb/acme.json"
