apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ing-car
    annotations:
#kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: t.51joinup.com
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-car
          servicePort: 80
