apiVersion: v1
kind: ReplicationController
metadata:
  labels:
      name: rc-car
  name: rc-car
spec:
  replicas: 2
  selector:
      app: pod-car
  template:
    metadata:
      labels:
          app: pod-car
    spec:
      containers:
        - name: nginx
          image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/nginx_51tywy:v1.0
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          volumeMounts:
            - name: nfs
              mountPath: "/usr/share/nginx/html"
            - name: imgserver
              mountPath: "/usr/share/nginx/html/uploads"
        - name: php
          image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/php:51tywy
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: nfs
              mountPath: "/usr/share/nginx/html"
            - name: imgserver
              mountPath: "/usr/share/nginx/html/uploads"

      volumes:
        - name: nfs
          hostPath:
            path: "/nfs_file/sites/car"
        - name: imgserver
          hostPath:
            path: "/nfs_file/img"
