apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql
  labels:
    name: pod-mysql
spec:
  containers:
    - name: mysql
      image: registry.cn-hangzhou.aliyuncs.com/zhg_docker_ali_r/mysql:5.7.17
      ports:
        - containerPort: 3306
          hostPort: 3307
          name: mysql
      securityContext:
        privileged: true
      env:
        - name: MYSQL_ROOT_PASSWORD
          # Change this password!
          value: "Zcar20171215"
      resources:
          limits:
            cpu: 100m
      volumeMounts:
        - name: mysql-nfs
          mountPath: "/var/lib/mysql"
  volumes:
    - name: mysql-nfs
      hostPath:
        path: "/nfs_file/mysqldata"
