apiVersion: v1
kind: Service
metadata:
    name: golang-anooc-svc
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: 80
      port: 80 
      nodePort: 30019
      protocol: TCP
    - name: https
      targetPort: 443
      port: 443
      nodePort: 30020
      protocol: TCP    
  selector:
    app: golang-anooc-pod-app
